version: '3.9'
services:
  users_app:
    build: .
    container_name: users-api
    image: rdcl-java-app:1.0.1
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://users-postgresql:5432/usersbdd
      - SPRING_DATASOURCE_USERNAME=rdario921
      - SPRING_DATASOURCE_PASSWORD=123456789
    depends_on:
      users_db:
        condition: service_healthy
    networks:
      - app-network

  users_db:
    container_name: users-postgresql
    image: postgres:latest
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=usersbdd
      - POSTGRES_USER=rdario921
      - POSTGRES_PASSWORD=123456789
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U rdario921 -d usersbdd" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
networks:
  app-network:
    driver: bridge